#ifndef NCNN_INCLUDE_GUARD_fp_id_h
#define NCNN_INCLUDE_GUARD_fp_id_h
namespace ncnn_param_id {
const int LAYER_input_1_0 = 0;
const int BLOB_input_1_0 = 0;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_dense_BiasAdd_ReadVariableOp_0 = 1;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_dense_BiasAdd_ReadVariableOp_0 = 1;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_conv2d_BiasAdd = 2;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_conv2d_BiasAdd_0 = 2;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_re_lu_Relu = 3;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_re_lu_Relu_0 = 3;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_max_pooling2d_MaxPool = 4;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_max_pooling2d_MaxPool_0 = 4;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_conv2d_1_BiasAdd = 5;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_conv2d_1_BiasAdd_0 = 5;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_re_lu_1_Relu = 6;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_re_lu_1_Relu_0 = 6;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_max_pooling2d_1_MaxPool = 7;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_max_pooling2d_1_MaxPool_0 = 7;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_conv2d_2_BiasAdd = 8;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_conv2d_2_BiasAdd_0 = 8;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_re_lu_2_Relu = 9;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_re_lu_2_Relu_0 = 9;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_max_pooling2d_2_MaxPool = 10;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_max_pooling2d_2_MaxPool_0 = 10;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_conv2d_3_BiasAdd = 11;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_conv2d_3_BiasAdd_0 = 11;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_re_lu_3_Relu = 12;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_re_lu_3_Relu_0 = 12;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_conv2d_3_BiasAdd__34 = 13;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_conv2d_3_BiasAdd__34_0 = 13;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_flatten_Reshape = 14;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_flatten_Reshape_0 = 14;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_dense_MatMul = 15;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_dense_MatMul_0 = 15;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_dense_BiasAdd = 16;
const int BLOB_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_dense_BiasAdd_0 = 16;
const int LAYER_StatefulPartitionedCall_siamese_net_StatefulPartitionedCall_sequential_dense_Sigmoid = 17;
const int BLOB_Identity_0 = 17;
} // namespace ncnn_param_id
#endif // NCNN_INCLUDE_GUARD_fp_id_h
